name: release-no-verify
# generating and publishing release package artifacts from the main branch
# based on release script for monai label: https://github.com/Project-MONAI/MONAILabel

on:
  workflow_dispatch:
    inputs:
      test_py:
        description: 'Publish package to test PY Repository'
        required: true
        default: 'true'
      main_py:
        description: 'Publish package to main PY Repository'
        required: true
        default: 'false'

jobs:
  packaging:
    if: github.repository == 'masadcv/torchmaxflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install wheel setuptools
          pip install -r requirements.txt
      - name: Build Package
        run: |
          python setup.py sdist bdist_wheel
#       - name: Verify Package
#         run: |
#           tmp_dir=$(mktemp -d)
#           cp dist/torchmaxflow* "$tmp_dir"
#           rm -r build torchmaxflow*.egg-info
#           # install from tar.gz
#           pip install "$tmp_dir"/torchmaxflow*.tar.gz
#           python -c 'import torch; import torchmaxflow; print(torchmaxflow.__file__)'
#           pip uninstall -y torchmaxflow
#           rm -r "$tmp_dir"
#         env:
#           shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/

      - name: Check artifacts
        run: |
          rm dist/torchmaxflow*.tar.gz
      - name: Publish distribution to Test PyPI
        if: ${{ github.event.inputs.test_py == 'true' }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution to PyPI
        if: ${{ github.event.inputs.main_py == 'true' }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
